#!/bin/bash

# ░█▀▄░█▀█░█▀▀░█░█░█▀▄░█▀▀
# ░█▀▄░█▀█░▀▀█░█▀█░█▀▄░█░░
# ░▀▀░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀

# Environment Variables
export EDITOR=nvim
export PATH=${PATH}:${HOME}/.local/bin
export DOTS=${HOME}/dots-for-android



source ${DOTS}/shell/prompt-colors


PS1="${R}[${G}nikin${P}@${B}netricsa${W}: ${Y}\W${R}]${C}\$${F} "

alias vi="nvim"

source /data/data/com.termux/files/usr/share/fzf/key-bindings.bash
source /data/data/com.termux/files/usr/share/fzf/completion.bash

