#!/bin/bash
#
# ░█▀▄░█▀█░█▀▀░█░█░░░█▀█░█░░░▀█▀░█▀█░█▀▀░█▀▀░█▀▀
# ░█▀▄░█▀█░▀▀█░█▀█░░░█▀█░█░░░░█░░█▀█░▀▀█░█▀▀░▀▀█
# ░▀▀░░▀░▀░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀

# Alias Definitions
alias vi="/usr/bin/nvim"
alias ls="ls -v --color=always --group-directories-first"
alias grep="grep --color=always"
alias less="less --quit-if-one-screen -X -RAW-CONTROL-CHARS"
alias fixmanuals="cd ~/storage/shared/equipment_manuals//"
# Function Definitions
#
function weather() {
  curl wttr.in/${1}
}


function cloudsync() {

    function pushNotes() {
        pushd ~/projects/notes
        branch=$(git branch | awk ' /\*/ {print $2} ')
        git pull
        git add --all
        git commit -m "o.O"
        git push -u origin ${branch} --verbose
        popd 
    }

    case $1 in 
        -n) pushNotes ;;
        *) pushNotes ;;
    esac
}

function def() {
    sdcv -n --utf8-output --color "$@" 2>&1 | \
        fold --width=$(tput cols) | \
        less --quit-if-one-screen -RX
    }
