#!/bin/bash

# ░█▀▄░█▀█░█▀▀░█░█░█▀▄░█▀▀
# ░█▀▄░█▀█░▀▀█░█▀█░█▀▄░█░░
# ░▀▀░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀

# Environment Variables
export EDITOR=nvim
export PATH=${PATH}:${HOME}/.local/bin

PS1="${R}[${G}\u${P}@${B}android${W}: ${Y}\W${R}]${C}\$${F} "




miti
