#!/data/data/com.termux/files/usr/bin/bash

data="$HOME/data.json"
key1=$(jq -r 'keys[]' "$data" | fzf) || exit 0
key2=$(jq -r --arg k1 "$key1" '.[$k1] | keys[]' "$data" | fzf) || exit 0

jq -r --arg k1 "$key1" --arg k2 "$key2" '.[$k1][$k2]' "$data" | termux-share -a send

if [[ $key1 == PAN* ]];
then
    :
fi
