#!/bin/bash

cowcenter() {
  local msg="$*"
  local width=$(tput cols)
  local output
  output=$(cowsay "$msg")
  local max_len=$(echo "$output" | awk '{print length}' | sort -nr | head -n1)
  local padding=$(( (width - max_len) / 2 ))
  echo "$output" | sed "s/^/$(printf '%*s' "$padding")/"
}



echo -ne "\e[?25l"


printf "\n%.0s" {1..20}

echo 📤 $(basename "`cat ~/.recentfile.txt`") | cowcenter

termux-open --send "`cat ~/.recentfile.txt`"
