#!/data/data/com.termux/files/usr/bin/bash
echo -ne "\e[?25l"

cols=$(tput cols)
rows=$(tput lines)

# Text to display
text="$(node ~/.local/bin/miti)"

# Calculate position
text_length=${#text}
col=$(( (cols - text_length) / 2 ))
row=$(( (rows / 3) + 0 ))

# Clear screen and move cursor
tput cup $row $col
echo "$text"

read -n 1 -s
